receivers:
  hostmetrics/system:
    collection_interval: 15s
    root_path: /hostfs
    scrapers:
      cpu:
      filesystem:
      load:
      memory:
      network:
      paging:
      process:
      processes:
  otlp/fromsdk:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

connectors:
  elasticapm: {}

processors:
  batch: {}
  elasticapm: {}

exporters:
  elasticsearch/otel:
    endpoints: ["http://elasticsearch:9200"]
    mapping:
      mode: otel

service:
  pipelines:
    traces/fromsdk:
      receivers: [otlp/fromsdk]
      processors: [elasticapm, batch]
      exporters: [elasticapm, elasticsearch/otel]
    metrics/fromsdk:
      receivers: [otlp/fromsdk]
      processors: [batch]
      exporters: [elasticsearch/otel]
    metrics/hostmetrics:
      receivers: [hostmetrics/system]
      processors: [batch]
      exporters: [elasticsearch/otel]
    metrics/aggregated-metrics:
      receivers: [elasticapm]
      processors: [batch]
      exporters: [elasticsearch/otel]
    logs/fromsdk:
      receivers: [otlp/fromsdk]
      processors: [batch]
      exporters: [elasticsearch/otel]
