export { ElasticsearchClient, isElasticsearchError } from "./client";
export type {
  ElasticsearchConnection,
  ElasticsearchError,
  EsqlError,
  EsqlColumn,
  EsqlResult,
  EsqlResponse,
  AsyncEsqlResult,
  EsqlQueryRequest,
  EsqlQueryParams,
  EsqlQueryResponse,
  ClusterInfoResponse,
  ResolveIndexResponse,
  GetDataStreamsResponse,
  DataStreamInfo,
  ResolveIndexDataStreamInfo,
  FieldCapsResponse,
  FieldCapability,
  UserCapabilities,
} from "./client";
